name: Static checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get python version
        run: |
          python_version=$(cat .python-version)
          echo "python_version=${python_version}" >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.local
            ~/.cache/pre-commit
          key: python-${{ env.python_version }}-poetry-1.5.1-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: '1.5.1'
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install Python ${{ env.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python_version }}
          cache: poetry

      - name: Install dependencies
        run: |
          make install

      - name: Linters
        run: |
          make lint

      - name: Unit Tests
        run: |
          make unit-tests
