name: Static checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install poetry
        shell: bash
        run: |
          pipx install poetry==1.4.2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Linters
        run: |
          make lint

      - name: Unit Tests
        run: |
          make unit-tests
